controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      j1:
        trajectory: 0.1
        goal: 0.1
      j2:
        trajectory: 0.1
        goal: 0.1
      j3:
        trajectory: 0.1
        goal: 0.1
      j4:
        trajectory: 0.1
        goal: 0.1
      j5:
        trajectory: 0.1
        goal: 0.1
      j6:
        trajectory: 0.1
        goal: 0.1
